export const GET_EVENT_REQUEST = "GET_EVENT_REQUEST";
export const ADD_EVENT_REQUEST = "ADD_EVENT_REQUEST";
export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
